=== pramineni01/webaml/webaml-schema/webaml.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "$id": "https://github.com/vaidasj/webaml/tree/master/webaml-schema/webaml.schema.json",
    "type": "object",
    "title": "WebAML v1.0 JSON schema",
    "description": "JSON Schema for Web-based algebraic modeling language",
    "additionalProperties": false,
    "required": [
        "name",
        "webamlVersion",
        "model"
    ],
    "properties": {
        "name": {
            "type": "string",
            "title": "The name of a model"
        },
        "description": {
            "type": "string",
            "title": "The description of a model"
        },
        "webamlVersion": {
            "type": "integer",
            "title": "Version of WebAML used for a model",
            "default": 1
        },
        "model": {
            "type": "object",
            "title": "Content of WebAML model",
            "required": [
                "sets",
                "parameters",
                "tables",
                "variables",
                "constraints",
                "objectives"
            ],
            "additionalProperties": false,
            "properties": {
                "sets": {
                    "type": "array",
                    "title": "All sets defined in a model",
                    "items": {
                        "type": "object",
                        "title": "WebAML set structure",
                        "required": [
                            "name",
                            "type",
                            "values",
                            "valueType"
                        ],
                        "additionalProperties": false,
                        "properties": {
                            "name": {
                                "type": "string",
                                "title": "Name of a set"
                            },
                            "type": {
                                "type": "string",
                                "title": "Type of a set",
                                "enum": ["SIMPLE"],
                                "description": "Currently only SIMPLE sets are supported.",
                                "default": "SIMPLE"
                            },
                            "values": {
                                "type": "array",
                                "title": "Values of a set",
                                "items": {
                                    "type": "string"
                                }
                            },
                            "valueType": {
                                "type": "string",
                                "title": "Data type of values in a set",
                                "enum": ["STRING", "NUMBER"]
                            },
                            "description": {
                                "type": "string",
                                "title": "The description of a set"
                            }
                        }
                    }
                },
                "parameters": {
                    "type": "array",
                    "title": "List of parameters in a model",
                    "items": {
                        "type": "object",
                        "title": "WebAML parameter structure",
                        "required": [
                            "name",
                            "type",
                            "values",
                            "valueType"
                        ],
                        "additionalProperties": false,
                        "properties": {
                            "name": {
                                "type": "string",
                                "title": "Name of a parameter"
                            },
                            "type": {
                                "type": "string",
                                "title": "Type of a parameter",
                                "enum": ["SCALAR", "INDEXED"],
                                "description": "Indexed parameters require indexes property to be provided."
                            },
                            "indexes": {
                                "type": "array",
                                "title": "Indexes as Sets for INDEXED parameters",
                                "items": {
                                    "type": "string"
                                }
                            },
                            "values": {
                                "type": "array",
                                "title": "Values of a parameter",
                                "items": {
                                    "type": "string"
                                }
                            },
                            "valueType": {
                                "type": "string",
                                "title": "Data type of values in a parameter",
                                "description": "FORMULA require to provide single values which contains expression to calculate",
                                "enum": ["NUMBER", "FORMULA"]
                            },
                            "description": {
                                "type": "string",
                                "title": "Description of a parameter"
                            }
                        }
                    }
                },
                "tables": {
                    "type": "array",
                    "title": "List of tables in a model",
                    "items": {
                        "type": "object",
                        "title": "WebAML table structure",
                        "required": [
                            "name",
                            "rows",
                            "columns",
                            "values",
                            "valueType"
                        ],
                        "additionalProperties": false,
                        "properties": {
                            "name": {
                                "type": "string",
                                "title": "Name of a table"
                            },
                            "rows": {
                                "type": "string",
                                "title": "Set to be used as rows index"
                            },
                            "columns": {
                                "type": "string",
                                "title": "Set to be used as columns index"
                            },
                            "values": {
                                "type": "array",
                                "title": "The values schema",
                                "items": {
                                    "type": "array",
                                    "items": {
                                        "type": "string"
                                    }
                                },
                                "description": "Two dimensional array of size rows x columns"
                            },
                            "valueType": {
                                "type": "string",
                                "enum": ["NUMBER"],
                                "title": "Data type of table cells"
                            },
                            "description": {
                                "type": "string",
                                "title": "Description of a table"
                            }
                        }
                    }
                },
                "variables": {
                    "type": "array",
                    "title": "List of variables in a model",
                    "items": {
                        "type": "object",
                        "title": "WebAML variable structure",
                        "required": [
                            "name",
                            "type"
                        ],
                        "additionalProperties": false,
                        "properties": {
                            "name": {
                                "type": "string",
                                "title": "Name of a variable"
                            },
                            "type": {
                                "type": "string",
                                "title": "Type of a variable",
                                "enum": ["CONTINUOUS", "BINARY", "INTEGER"]
                            },
                            "indexes": {
                                "type": "array",
                                "title": "Sets as indexes for array variables",
                                "items": {
                                    "type": "string"
                                }
                            },
                            "value": {
                                "type": ["string", "null"],
                                "title": "Fixed value of a variable",
                                "default": null
                            },
                            "bounds": {
                                "type": "array",
                                "title": "Lower and upper bounds of a variable",
                                "maxItems": 2,
                                "minItems": 2,
                                "items": {
                                    "type": ["string", "null"]
                                }
                            },
                            "description": {
                                "type": "string",
                                "title": "Description of a variable"
                            }
                        }
                    }
                },
                "constraints": {
                    "type": "array",
                    "title": "List of constraints in a model",
                    "items": {
                        "type": "object",
                        "title": "WebAML constraints structure",
                        "required": [
                            "name",
                            "type",
                            "value"
                        ],
                        "additionalProperties": false,
                        "properties": {
                            "name": {
                                "type": "string",
                                "title": "Name of a constraint"
                            },
                            "type": {
                                "type": "string",
                                "title": "Type of constraint",
                                "enum": ["INDEXED", "SIMPLE"]
                            },
                            "indexes": {
                                "type": "array",
                                "title": "The indexes schema",
                                "description": "Required if constraint type is INDEXED",
                                "items": {
                                    "type": "string"
                                }
                            },
                            "value": {
                                "type": "string",
                                "title": "Value of a constraint as a AsciiMath expression"
                            },
                            "description": {
                                "type": "string",
                                "title": "Description of a constraint"
                            }
                        }
                    }
                },
                "objectives": {
                    "type": "array",
                    "title": "List of objectives",
                    "description": "Currently only one objective per model is supported",
                    "maxItems": 1,
                    "minItems": 1,
                    "items": {
                        "type": "object",
                        "title": "WebAML objective structure",
                        "required": [
                            "name",
                            "type",
                            "value"
                        ],
                        "additionalProperties": false,
                        "properties": {
                            "name": {
                                "type": "string",
                                "title": "Name of a objective function"
                            },
                            "type": {
                                "type": "string",
                                "title": "Type of objective function",
                                "enum": ["MAXIMIZE", "MINIMIZE"]
                            },
                            "value": {
                                "type": "string",
                                "title": "Value of a objective function as a AsciiMath expression"
                            },
                            "description": {
                                "type": "string",
                                "title": "Description of a objective function"
                            }
                        }
                    }
                }
            }
        }
    }
}

=== pramineni01/webaml/webaml-schema/examples/transportation.json
{
  "name": "Transportation Problem",
  "description": "Minimizing transportation cost from multiple origins to multiple destinations",
  "webamlVersion": 1,
  "model": {
    "sets": [
      {
        "name": "i",
        "type": "SIMPLE",
        "values": ["Seattle", "San-Diego"],
        "valueType": "STRING",
        "description": "Canning plants"
      },
      {
        "name": "j",
        "type": "SIMPLE",
        "values": ["New-York", "Chicago", "Topeka"],
        "valueType": "STRING",
        "description": "Markets"
      }
    ],
    "parameters": [
      {
      	"name": "f",
      	"type": "SCALAR",
      	"values": ["90"],
        "valueType": "NUMBER",
      	"description": "Freight in dollars per case per thousand miles"
      },
      {
      	"name": "a",
      	"type": "INDEXED",
      	"indexes": ["i"],
      	"values": ["350", "600"],
        "valueType": "NUMBER",
      	"description": "Capacity of plants in cases"
      }, 
      {
      	"name": "b",
      	"type": "INDEXED",
      	"indexes": ["j"],
      	"values": ["325", "300", "275"],
      	"valueType": "NUMBER",
      	"description": "Demand at markets in cases"
      }, 
      {
      	"name": "c",
      	"type": "INDEXED",
      	"indexes": ["i", "j"],
      	"values": ["f * d_(i,j) / 1000"],
      	"valueType": "FORMULA",
      	"description": "Transport cost in thousands of dollars per cases"
      }       
    ],
    "tables": [
      {
      	"name": "d",
      	"rows": "origin",
      	"columns": "destination",
      	"values": [
      		["2.5", "1.7", "1.8"],
      		["2.5", "1.8", "1.4"]
      	],
        "valueType": "NUMBER",
      	"description": "Distance in thousands of miles"
      }
    ],
    "variables": [
      {
      	"name": "c",
      	"type": "CONTINUOUS",
      	"indexes": ["i", "j"],
      	"value": null,
      	"bounds": ["0", null],
      	"description": "Transport cost in thousands of dollars per cases"
      }  
    ],
    "constraints": [
      {
      	"name": "supply",
      	"type": "INDEXED",
      	"indexes": ["i"],
      	"value": "sum_j x_(ij) <= a_i",
      	"description": "Observe supply limit at plant"
      },
      {
      	"name": "demand",
      	"type": "INDEXED",
      	"indexes": ["j"],
      	"value": "sum_i x_(ij) >= b_j",
      	"description": "Satisfy demand at market"
      }      
    ],
    "objectives": [
      {
      	"name": "cost",
      	"type": "MINIMIZE",
      	"value": "sum_i sum_j c_(ij) * x_(ij)",
      	"description": "MINIMIZE transportation cost"
      }
    ]
  }
}
